# Generated by Django 5.0.6 on 2024-08-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("sid", models.IntegerField(primary_key=True, serialize=False)),
                ("sname", models.CharField(max_length=40)),
                ("sage", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
